CREATE TABLE usuario(
    Id VARCHAR(255) PRIMARY KEY,
    Username VARCHAR(255) NOT NULL,
    Nome VARCHAR(255) NOT NULL,
    DataNascimento DATE,
    Genero VARCHAR(50),
    Estado VARCHAR(255),
    Cidade VARCHAR(255),
    Email VARCHAR(100),
    Curso VARCHAR(255),
    Senha VARCHAR(255) NOT NULL,
    DataCadastro DATE NOT NULL
);

CREATE TABLE CHAT (
    Id VARCHAR(255) PRIMARY KEY,
    CriadoEm DATE NOT NULL
);

CREATE TABLE PARTICIPANTES_CHAT (
    Id VARCHAR(255) PRIMARY KEY,
    UsuarioId VARCHAR(255),
    ChatId VARCHAR(255),
    FOREIGN KEY (UsuarioId) REFERENCES usuario(Id),
    FOREIGN KEY (ChatId) REFERENCES CHAT(Id)
);

CREATE TABLE MENSAGEM (
    Id VARCHAR(255) PRIMARY KEY,
    UsuarioId VARCHAR(255),
    ChatId VARCHAR(255),
    Texto TEXT NOT NULL,
    EnviadoEm DATE NOT NULL,
    FOREIGN KEY (UsuarioId) REFERENCES usuario(Id),
    FOREIGN KEY (ChatId) REFERENCES CHAT(Id)
);

CREATE TABLE ESTUDANTE (
    Id VARCHAR(255) PRIMARY KEY,
    UsuarioId VARCHAR(255),
    FOREIGN KEY (UsuarioId) REFERENCES usuario(Id)
);

CREATE TABLE VOLUNTARIO (
    Id VARCHAR(255) PRIMARY KEY,
    UsuarioId VARCHAR(255),
    FOREIGN KEY (UsuarioId) REFERENCES usuario(Id)
);

CREATE TABLE PERFIL (
    Id VARCHAR(255) PRIMARY KEY,
    UsuarioId VARCHAR(255),
    Biografia TEXT,
    FotoPerfil VARCHAR(255),
    FOREIGN KEY (UsuarioId) REFERENCES usuario(Id)
);
